-- Newsletter schema
-- The canonical table is public.newsletter_subscribers defined in supabase-schema.sql.
-- All functions (newsletter_signup, admin-list-leads, admin-export-leads) use that table.
-- This file is kept for reference only; see supabase-schema.sql for the authoritative definition.
